eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8082
spring:
  application:
    name: clientIndex
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh