server:
  port: 8102
  #http://localhost:8080/EUREKACLIENT/index  访问网站
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info